### ISSUE TITLE
DropZoneId undefined

### ISSUE THREAD

**Issue by M-Blobby** [cluetec/ngcx-tree#112]
First of all, thank you for this library which works very well. However, I have noticed an issue where sometimes the drop function does not work. This remains very rare but still occurs, and I was able to reproduce it using the demo link. Upon closer inspection, I noticed that the `dropZoneId` variable within the `handleDragRelease` method was undefined. The value of `<any>event.event.target` was equal to `<div class="drop-insert-line"></div>`.

https://github.com/cluetec/ngcx-tree/assets/3278715/6f3b5204-021d-4684-b367-a56dad745fdf

To correct this, a solution would be to check the parent if dropZoneId is undefined:

```typescript
const target = <HTMLDivElement>event.event.target;
const dropZoneId = target.id || target.parentElement?.id;
if (!dropZoneId) {
  // no valid drop zone
  return;
}
```

What do you think? If the solution seems relevant, I would be happy to open a PR.

**Comment by mn-42** [comment]
thank you for your issue and the fix. I used it in next version 17.0.1.

Seems to work properly now. :)
